version: "3.3"  # optional since v1.27.0

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./src/:/usr/share/nginx/html/
      - logvolume01:/var/log
    links:
      - redis

  redis:
    image: redis

volumes:
  logvolume01: {}
